version: 0.2

phases:
  install:
    commands:
      - apt-get update
      - apt-get install -y nginx

  build:
    commands:
      - echo "Copying files to /var/www/html..."
      - mkdir -p /var/www/html
      - cp index.html ten.css ten.js /var/www/html/

  post_build:
    commands:
      - echo "Starting Nginx to serve the static site..."
      - nginx -g "daemon off;" & # Start Nginx without systemd

artifacts:
  files:
    - index.html
    - ten.css
    - ten.js
